services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./birds/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_ENABLE_PROXY_FIX: "True"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app_network

  flask_app:
    build: ./birds
    container_name: flask_app
    environment:
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/myapp
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./birds:/app
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
